### ISSUE TITLE
"insecure" nested dev dependencies lowering project score

### ISSUE THREAD

**Issue by yyx990803** [bithound/feedback#106]
Does this really make sense? I appreciate the fact that bithound is pointing out potential security concerns, but as a project author, I have very little control over a dev dependency nested 3 levels deep - the only thing I can do is wait until maintainers of my direct dependencies fix their dependencies.

And just because some of dev dependencies nested 3 layers deep are depending on an outdated version of uglifyjs, my project score went from 95 to 89? This alone would make me no longer want to display the badge in the project README.

**Comment by dansilivestru** [comment]
Hi @yyx990803,

Apologies for the long reply here.

The short answer is yes, at least in our opinion. Let me start by saying that the vulnerability we are reporting here is for UglifyJS which is used for minifying code and could cause a real vulnerability in production. Full report can be found here: https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons

Seeing that in today's world the majority of the code used and shipped by many projects is actually 3rd party code, it seems very important to score our usage of these dependencies, even if they are nested. It is difficult to determine which vulnerability might impact a project vs another, and we prefer to err on the side of caution here. We’re here to report these issues. Taking action on the reported issues is completely up to you, but you will be doing so having had all the facts at hand. 

I realize that none of us have direct influence over the 3rd party dependencies that we include in our projects. In a way that's part of the problem! We reduce your score by far less for nested insecure dependencies both because of your lack of control as well as the fact that your actual exposure to that vulnerability is reduced the further the nesting. We display deeply nested vulnerabilities, but only those three levels down or less actually affect your score.

Actions that we can all take to help foster a more secure NPM environment for the entire JS community include issuing PRs to projects that are directly vulnerable or commenting on already existing PRs to help move the process along.

You'll notice that handlebars has already been updated and a new release put out bumping UglifyJS to the new and secure version: https://github.com/wycats/handlebars.js/pull/1084

We hope that by exposing these issues and making them relevant to projects that use these kinds of dependencies (nested or not) will help drive fast resolution.

I would very much love to hear your thoughts on how we score dependencies and if you feel there are some things we can do better.

**Comment by yyx990803** [comment]
I agree that exposing these issues are important and helpful. However, I display the bithound badge in my repo primarily to showcase **quality of my code**. I'd be happy if I can display a badge that shows only the code insight score.

In addition, all 3 dependencies on uglifyjs in my repo **are** 3 levels deep, yet it lowers my score from 95 to 89, which I think is too much.

**Comment by carlosperez** [comment]
Hi @yyx990803 – We're always looking at how to better tweak the scoring of dependencies, and the deeper we get with our analysis, the more we will be tweaking it. I understand the frustration of not being able to directly impact the score when a module's vulnerability is deeply nested. The justification of the score impact is so that's things don't appear to be be "fine" when they might reveal a a deeper problem. Our score is one of the ways we communicate the need for action, thus the score being dropped. If it was a very minimal change, it might go unnoticed. 

By the way – I took a look at the dependencies on `vuejs/vue` and it looks like things are in great shape. I noticed the Unused badge on the envify dependency. My guess is that is actually being used, but maybe in a way that bitHound can't detect it. You can actually have bitHound not mark modules as unused with `.bithoundrc` --> [see here for details](http://blog.bithound.io/configuring-bithound-101/#ignoringmodulesmarkedasunused). 

We're going to close this issue and track dependency score changes internally.
