### ISSUE TITLE
for dependencies ^2.6.0 == 2.6.0

### ISSUE THREAD

**Issue by mathiasrw** [bithound/feedback#108]
I see the following on https://www.bithound.io/github/agershun/alasql/develop/dependencies/npm

>     gulp-concat
>     Requested: ^2.6.0 | Stable: 2.6.0

the problem is that ^2.6.0 **does** represent the last stable version 2.0.6

Please consider https://docs.npmjs.com/files/package.json for valid ways of naming versions to depend on in package.json :

```js
{ "dependencies" :
  { "foo" : "1.0.0 - 2.9999.9999"
  , "bar" : ">=1.0.2 <2.1.2"
  , "baz" : ">1.0.2 <=2.3.4"
  , "boo" : "2.0.1"
  , "qux" : "<1.0.0 || >=2.3.1 <2.4.5 || >=2.5.2 <3.0.0"
  , "asd" : "http://asdf.com/asdf.tar.gz"
  , "til" : "~1.2" // same as "^1.2.3"
  , "elf" : "~1.2.3"
  , "two" : "2.x"
  , "thr" : "3.3.x"
  , "lat" : "latest"
  , "dyl" : "file:../dyl"
  }
}
```

**Comment by dansilivestru** [comment]
Hi @mathiasrw I don't think this is a bug, please allow me to explain...

If a dependency has been identified as being insecure, deprecated, outdated, or unused we will display a badge next to it. If everything is good, there is no badge. We didn't feel that we needed to call out the fact that everything was fine, but perhaps that would be an option to clarify things?

We do always show you the Requested Vs. Stable for informational reasons, not to indicate that anything is wrong.

Of course, I might be misunderstanding your comments above, so please let me know if I missed the mark. Also, would love your thoughts on my explanation.

Thanks again!

**Comment by mathiasrw** [comment]
Ahh - I get it. 

Ok - Ill change this issue to an input: its not easy to see that everything is OK as the bithound batch is orange. It looks like its kind og not good as a dependency (but its actually fine - but the code could be better)

I recommend that if its all good that you write one of the following instead of `Requested: xxxx | Stable: yyy`

- `All good` 
- `All good: fetching yyy`

**Comment by fhemberger** [comment]
There still seems to be an issue with this: I just updated some projects with vulnerable dependencies to the latest version (including the security fixes), yet the package is still shown as vulnerable:

![](https://cloud.githubusercontent.com/assets/153481/9830792/02a53506-593c-11e5-8e1c-a1f1f3af1886.png)

**Comment by itssamlowe** [comment]
Hey @fhemberger Appears that lab relies on other dependencies that are insecure (eslint, handlebars): https://www.bithound.io/github/hapijs/lab Which is why it's still showing up as such.

**Comment by fhemberger** [comment]
@itssamlowe Hmm, checking against nodesecurity.io with `nsp audit-package`, lab 5.16.1 seems to be clean.

**Comment by fhemberger** [comment]
mocha@latest is listed as "insecure" on the dependency list of jade:
https://www.bithound.io/github/jadejs/jade

Looking at the mocha page itself, I don't see any security notice:
https://www.bithound.io/github/mochajs/mocha

**Comment by CSilivestru** [comment]
Hi @fhemberger,
We don’t run ​​`nsp audit-package`​​ to analyze insecure dependencies — we run some custom analysis on that front but use data provided by nsp. We believe that if a dependency uses and insecure dependency, that initial dep should be considered vulnerable.

In terms of your mocha example, jade is still listed as using an insecure package of mocha because mocha’s latest release is 2.3.2. That release, ironically, is using a insecure version of jade. However, on ​​`master`​​ branch (which is what the bitHound dashboard reports on), mocha has since reverted their version of jade to a non-vulnerable version and is ‘clean’ again. You can see that revert in this commit: https://github.com/mochajs/mocha/commit/ea3b6524f66026321cf86aedbc0af3fc20b5faec#diff-b9cfc7f2cdf78a7f4b91a753d10865a2.

So, requiring latest for mocha retrieves version 2.3.2, which requires insecure packages. When mocha releases their next version, that security warning should go away (assuming no other insecure package are introduced).

We can certainly understand how the discrepancy between current analysis and latest release version analysis may cause some confusion. I’ve opened up an internal issue to help make cases like this more clear.

**Comment by fhemberger** [comment]
Great, thank you for the info!
