### ISSUE TITLE
Insecure DEPENDENCIES

### ISSUE THREAD

**Issue by JosefJezek** [bithound/feedback#109]
Could you create tree of insecure packages? I would like create issues on github for this packages.

I can not resolve Insecure DEPENDENCIES in short time. :-(

https://www.bithound.io/github/StartPolymer/polymer-starter-kit-plus

**Comment by fhemberger** [comment]
As bithound is using the nodesecurity.io API, this should not be a problem, as the tree is returned anyway.

**Comment by fhemberger** [comment]
And also a big :100: on this. It's almost impossible for some repositories to remove the "insecure" flag, because the vulnerable (dev)dependency is rooted several levels deep. A tree view would tremendously help to send out pull requests to get those packages updated.

**Comment by carlosperez** [comment]
Hi @fhemberger and @JosefJezek – On the dependency view itself (rather than the project dashboard), we do show a path of where the vulnerability is stemming from (the packages and versions).

This screenshot shows that the vulnerability of web-component-tester follows a path of `web-component-tester -> bower -> handlebars -> uglify-js` 

![screen shot 2015-09-15 at 9 41 31 am](https://cloud.githubusercontent.com/assets/1263213/9877966/1756d8e8-5b8e-11e5-9253-ae67b19aba99.png)

We're looking at ways of improving our dependency results to make the problem clearer, and more actionable, so be on the lookout for that. 

Admittedly, it is indeed difficult to remove all insecure dependencies because the problem can be very widespread and deeply rooted. It's part of the problem we're hoping we can help solve.

**Comment by fhemberger** [comment]
@carlosperez Ah, sorry. Haven't noticed that view at all!

All we need now is a tool creating issues/PRs automatically to get rid of those old uglify-js and semver versions. ;)

**Comment by gtanner** [comment]
Looks like this is closed.

And we are working on some cool stuff @fhemberger ;)
