### ISSUE TITLE
how do you sign in

### ISSUE THREAD

**Issue by davidosomething** [bithound/feedback#24]
from the homepage!??

**Comment by CSilivestru** [comment]
Hi @davidosomething,

Currently, the bitHound application is separate from the rest. It looks like you're trying to sign in from www.bithound.io rather than from app.bithound.io.

During closed beta, we were keeping those parts separate but we are actively working on merging the two and that will be out soon :-).

To sign in, please go to https://app.bithound.io.
Thanks!
