### ISSUE TITLE
should not count documentation in total line count

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#29]
too many lines are defined as maintainability issue, but it also counts all the jsdoc for example.
makes more sense to count actually js code lines.

**Comment by carlosperez** [comment]
Hi @sagiegurari – this is a bit of a grey area as the length of the file does affect maintainability. For example commented out code should definitely be taken into consideration. 

Rest assured we are working on it.

**Comment by sagiegurari** [comment]
commented out code is a problem by itself :) and should not be in a file at all (unless you got some TODO in the begining) but wouldn't mix that and documentation.
for js, the standard is jsdoc which can easily be identified by the '@' type tags.

**Comment by rexxars** [comment]
+1 for not counting jsdoc as complexity

**Comment by sagiegurari** [comment]
any updates on this one?

**Comment by gtanner** [comment]
Still leading to some internal debates :)

There is a part of me that wants to agree with you, but classification of comments for scoring is something that is on the R&D backlog.

When you think of some example classification of comments:
- Commented out code
- TODO / HACKS
- License Headers
- JSDoc
- Code Annotations

The weighting of those type of comments in regards to maintenance is a fun problem.

Comments don't have the luxury of being run (well I guess JSDoc comments kind of do), and they do require "maintenance" to be kept up to date.

If we were to weigh each of these classifications against the "maintenance value of one line of code" they start to be approx the same weight of the code IMHO.

The only classification that really ends up close or near to a zero weight would be a license header, since that is more of a fire and forget comment.

**Comment by sagiegurari** [comment]
1. Actually I was in a situation that we had to put license headers and the company changed name so all files had to be updated :)
2. Jsdoc need to be validated but if you count it in the total line count you encourage docless code. We should not aim that.
Too many people see docs as something not important, but for someone who uses many diff libs, api docs are extremely helpful to understand the lib capabilities.
3. TODOs should lower score
4. Commented out code should count in the total lines as it is code that was left in the file instead of being deleted.

**Comment by CSilivestru** [comment]
Hi @sagiegurari and @rexxars,

These are all very good points and have been actively discussed within the team here. As of late, however, our focus as been on dependencies and security but we have not forgotten this feedback!

We'll move to start tracking this internally and I suggest you keep up with our newsletter, [changelog](https://www.bithound.io/changelog) and [blog](http://blog.bithound.io) for future feature updates :-). If you'd like to get in touch, feel free to use our in-app messaging service! Thanks for all the great feedback so far.
