### ISSUE TITLE
Where is documentation on all options for .bithoundrc

### ISSUE THREAD

**Issue by kof** [bithound/feedback#30]
For e.g. I am looking for a way to ignore all this semicolon warnings. 

https://www.bithound.io/jsstyles/jss

**Comment by CSilivestru** [comment]
Hi @kof,

`.bithoundrc` is only currently used for ignoring files.

We use jshint as our lint reporter. That particular warning is generated by that.
You can configure jshint by committing a `.jshintrc` and a `.jshintignore` to your root directory and bitHound will use those instead of a default configuration when linting your files.
In this case, adding a `.jshintrc` is what you'd want to do.

It follows a basic format of:
```
{
    property: value
}
```

The documentation for all options can be found here: http://jshint.com/docs/options/

Please let me know if you have any other questions -- I'll keep this open until you report back that those errors are now ignored :-).

Happy coding!

**Comment by gtanner** [comment]
Gonna close this for now :) feel free to open this if you have any more questions @kof
