### ISSUE TITLE
My repo takes forever to be analysed (literally)

### ISSUE THREAD

**Issue by sfermigier** [bithound/feedback#35]
https://www.bithound.io/co-ment/comt (been analysing for more than 5 hours now).

**Comment by dansilivestru** [comment]
Thanks for letting us know. The team is looking into it. We'll keep you posted.

**Comment by benleb** [comment]
same problem here with two very small repos... wannundwo/wuw_server & benleb/ffmoodle

**Comment by dansilivestru** [comment]
Hi @benleb Thanks for letting us know, I just checked both of those. They were not analyzed at all when I visited them. They both completed for me in seconds and have good scores :-)

Can you please confirm that you were signed to bitHound when you tried to have those repos analyzed?

**Comment by benleb** [comment]
Ok, it seems this is an issue with chrome, in safari your hole page gots more functionality (settings menu, the actual errors are shown (not just how much like in chrome),... maybe µBlock ad-blocker caused this, after disabling everything works in chrome too. and - crazy - after reenabling, it continues to work...

so its solved for me, crazy issue... thanks!

**Comment by gtanner** [comment]
Hey @sfermigier, your repo is analyzed as well.

I know we did a release this weekend that had some updates to process some of the failing repos (which yours was one of).  

Sorry for the lack of communication on the timing of this fix because it got caught up in a much larger feature (https://www.bithound.io/changelog).

Cheers.
