### ISSUE TITLE
Simple switch qualified as too complex

### ISSUE THREAD

**Issue by moissinac** [bithound/feedback#51]
Here
https://www.bithound.io/github/moissinac/SuperPath/blob/84db36c1d78340fadd9ac8fcdfbe22b836bf3b12/Js/SuperPathExpander.js
my code has a switch with about 10 simple 'case'
bithound qualify that part of the code as too complex
So, I'm curious to know how you suggest to do 'good' code in such a very simple and common case

**Comment by gtanner** [comment]
This is a very good question, lets see if I can answer this over the internet :)

Example:

    function action(input) {
      var command = input[0], result;

      switch(command) {
        case 'A':
        case 'a':
          result = 'A' + input;
          break;
        case 'B':
        case 'b':
          result = 'B' + input;
          break;
        case 'C':
        case 'c':
          result = 'C' + input;
          break;
        //many more tokens
        default:
          break;
      }

      return result + ' acted upon';
    }

Complexity is high because of all the branches for the case statement, if we were to start to think about
what this function is doing though, it is really doing two things.  Firstly it is extracting out a token from the input and then for each type of token it acts upon it.

A quick refactor to split out these two processes gives us this:

    var tokens = {
      "a": function (input) {
        return 'A' + input;
      },
      "b": function (input) {
        return 'B' + input;
      },
      "c": function (input) {
        return 'C' + input;
      },
      "default": function (input) {
      }
    };

    function action(input) {
      var cmd = input[0].toLowerCase(),
          token = tokens[cmd] || tokens.default;

      return token(input) + ' acted upon';
    }

This ends up giving us two modules which are now much easier to test and reason about in isolation.

In the end you can end up with extracting out a true lexer from your token parsing code and have more focused and easy to test modules.

Thoughts?

**Comment by moissinac** [comment]
Great! Thank's
Your explanation is very clear and useful

**Comment by gtanner** [comment]
Glad I could help!
