### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by dozoisch** [bithound/feedback#60]
Hi! 

As of #14, I've seen that you guys now support React and JSX. I am a React-Bootstrap collaborator, and we're trying to get our code analyzed on [BitHound][rb-analysis], but it seems to fail (saying that it's looking for a regex).

See:

https://www.bithound.io/github/react-bootstrap/react-bootstrap/blob/f2f220633512e6fd0bb2ee8866823ddc455c8236/src/ListGroup.js#53-lint

[rb-analysis]: https://www.bithound.io/github/react-bootstrap/react-bootstrap/master

**Comment by gtanner** [comment]
Hey @dozoisch:

we noticed this a little bit ago (and lost track of it because it was on a closed issue). https://github.com/bithound/feedback/issues/14

I am switching out parsers at the moment and add this repo to my suite of tests.

Glad to have you on board!

I was using the facebook parser and not babel, which was failing in some cases.

**Comment by dozoisch** [comment]
@gtanner Great! Thanks a lot!

**Comment by gtanner** [comment]
Hey @dozoisch,

Rolled out the new JSX parser.  There are a couple of weird matches for lint (the ```...var``` splat lines which you ingore via es-lint) but is much better.

I am starting to look into eslint as per #61, so that would help clean these up.

**Comment by dozoisch** [comment]
Cool! Thanks a lot!
