### ISSUE TITLE
Engine or flags

### ISSUE THREAD

**Issue by mathiasrw** [bithound/feedback#71]
**A few questions:**

A) Are there any plans to expand the .bithound file to includ flags for the linting?

B) Are there any plans to expand with more "linting engines" so you can select JSlint, JShint, ESlint .... from your .bithound file?

**Input:**

Who truely cares about what errors are in the code? What's important is how to solve the issues... 

In bithound I often have a feeling that I have (really good) information about something that could be better - but feel a bit abaoondond with the issues. I believe bithound can be tamed to do more than barking - it can sniff up info and walk with me into the world so I feel more safe because we are two who walk the path together. 

Example: Would be so awesome if you made it easy to go from a lint error directly to the right spot on jslinterrors.com to help SOLVE the thing...

**Comment by dansilivestru** [comment]
Hi @mathiasrw Thanks! Let me try and answer your points.

A) Right now we only support JSHint. We do however respect any rules that you would have in your .jshintrc and .jshintignore files. More details here: https://www.bithound.io/blog/post/customizing-jshint-on-bithound

B) We have plans to support ESlint and JSCS in the future. JSlint is not on our roadmap since we've found that many developers no long like it's restrictive nature. Rather than you having to specify which linter you want us to use, we will likely have a default and switch to use your prefered linter based on which configuration files you have checked into your repository.

I agree with your input on giving more guidance as to how to solve the issues we report. We did look into jslinterrors.com as a source for this information but found that it was lacking. That was a while ago, so we'll revisit the project.

I'll keep this issue open so we can keep you posted on progress.


jslinterrors.com

**Comment by mathiasrw** [comment]
Thanks for a great answer. 

I just noticed that jslinterrors has an API to intergrate http://jslinterrors.com/api/

Dont know about the quality - but im sure they would love some help from bithound to get the quality up and running so everybody can benefit :)

**Comment by dansilivestru** [comment]
Hi @mathiasrw 

This is something that's still on our roadmap, but I wanted to quickly update this issue to let you know we do support ESLint now: http://blog.bithound.io/eslint-support-on-bithound/

Rather than having to specify which linter you'd like us to use, we decided to look at your project instead.

 - If you have no config, we'll run jshint
 - If you've specified a .jshintrc again, we'll run jshint
 - If you've specified a .eslintrc, we'll run ESLint (please note, we only support ESLint 1.0.0 and higher at the moment)

I'm going to close this issue and open a new one that deals with the http://jslinterrors.com/api/ feature request.

**Comment by mathiasrw** [comment]
Sounds great !
