### ISSUE TITLE
Got `Strings must use singlequote.` on a line that doesn't have a string

### ISSUE THREAD

**Issue by jeffcharles** [bithound/feedback#87]
Take a look at https://www.bithound.io/github/jeffcharles/poleland/blob/110c73f9135907028d743ef774d8ed099f67c7d5/web-client/components/poll.jsx#9-lint.

**Comment by CSilivestru** [comment]
Hi @jeffcharles,

My apologies for the delay in getting back to you! Thanks for reporting this.
We're currently aware of some oddities in our jsx linting and are exploring solutions around it.

We'll keep this issue updated as we work towards a fix.
Thanks!

**Comment by dansilivestru** [comment]
Hi @jeffcharles 

With our recent release of ESLint support, this issue is essentially resolved. You will need to introduce a ESLint along with .eslintrc into your project for us to properly analyze your jsx files. We've had to move to this approach due to the fact that JSXHint (which we were using before) has been officially deprecated in favour of ESLint.

You can find more details on our ESLint release here: http://blog.bithound.io/eslint-support-on-bithound/

I'm going to close this is for now, but please do re-open if you have any questions or would like more info.
