### ISSUE TITLE
"Something went wrong while analyzing this repo"

### ISSUE THREAD

**Issue by yyx990803** [bithound/feedback#95]
<img width="827" alt="screen shot 2015-08-18 at 12 53 52 pm" src="https://cloud.githubusercontent.com/assets/499550/9336559/3e8cf074-45a8-11e5-9875-68ce5a0e51a1.png">

And it seems the analysis never finishes. Is there anyway to force a refresh?

**Comment by gtanner** [comment]
can you let us know which repo?

**Comment by yyx990803** [comment]
https://www.bithound.io/github/yyx990803/vue

**Comment by gtanner** [comment]
Thanks, looking into it.

**Comment by gtanner** [comment]
Thanks for reporting this @yyx990803.

Deployed a fix and reprocessed your repo: https://www.bithound.io/github/yyx990803/vue

The problem was a few vendor files were not ignored (see https://www.bithound.io/github/yyx990803/vue/blob/213b5394dcabb72abf2992e6228d3de740c498c2/test/unit/lib/jasmine.js) and had A LOT of lint errors (13K or so).

I added in the `max-lint` feature on our eslint check to cap these files to 100 lint max (and display the `max-lint` badge).
